name: Deploy Svelte components

on: [push]

# env:
#     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: |
                  npm install -D --force esbuild
                  npm ci --ignore-scripts
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Security audit
              run: npm audit --audit-level=moderate --omit=dev --force

            # - name: Check Lint errors
            #   run: npm run lint

            - name: Check Typescript errors
              run: npm run check

            - name: Check spelling errors
              run: npm run spell

            # - name: Install Playwright (for tests)
            #   run: npx playwright install --with-deps

            # - name: Build Histoire
            #   run: npm run story:build

            # - name: Serve Histoire stories
            #   run: npm run story:preview &

            # - name: Wait for Histoire server
            #   run: ./bin/wait-for-histoire.sh

            # https://storybook.js.org/tutorials/ui-testing-handbook/react/en/automate/
            # - name: Run Playwright tests
            #   run: npm run test:ci

            - name: Package components
              run: npm run build

            - name: Publish to NPM
              run: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
