name: Test and publish module

on:
    push:
        tags:
            - v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: |
                  npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
                  npm ci --ignore-scripts
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Run unit test
              run: 'npm test'

            - name: Publish to NPM
              run: npm publish --access public
