name: Package Svelte components and deploy to NPM.

on:
    push:
        branches:
            - publish
        # tags:
        #     - v*.*.*

jobs:
    # Single deploy job since we're just deploying
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: |
                  npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
                  npm ci --ignore-scripts
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install Playwright (for tests)
              run: npx playwright install --with-deps

            # Testing locally doesn't work with svelte csf:
            # https://storybook.js.org/tutorials/ui-testing-handbook/react/en/automate/
            # - name: Run Storybook tests
            #   run: ./node_modules/.bin/test-storybook
            #   env:
            #       TARGET_URL: '${{ github.event.deployment_status.target_url }}'
            #  OR
            # - name: Serve Storybook and run tests
            #   run: |
            #       npx concurrently -k -s first -n "Storybook,tests" -c "green,blue" \
            #       "npx http-server static --port 6006 --silent" \
            #       "npx wait-on tcp:6006 && ./node_modules/.bin/test-storybook"
            - name: Run Storybook tests
              run: ./node_modules/.bin/test-storybook --url https://ui.surveyplanet.com
              # env:
              #     TARGET_URL: '${{ github.event.deployment_status.target_url }}'

            - name: Package components
              run: npm run package

            - name: Publish !! - DRY RUN - !!
              run: cd package && npm publish --access public --dry-run
